In [25]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
import matplotlib.ticker as ticker
import datetime as datetime
import requests
import json
import time

In [46]:
start_time = time.time() - 200*60*60
resource = requests.get("https://poloniex.com/public?command=returnChartData&currencyPair=BTC_ETH&start=%s&end=9999999999&period=1800" % start_time)
data = json.loads(resource.text)

quotes = {}
quotes['open']=np.asarray([item['open'] for item in data])
quotes['close']=np.asarray([item['close'] for item in data])
quotes['high']=np.asarray([item['high'] for item in data])
quotes['low']=np.asarray([item['low'] for item in data])

In [47]:
import pandas as pd
def sgn(x):
    return 1 if x >= 0 else -1
X = quotes['close'] - quotes['open']
y = [sgn(i) for i in X]
df = pd.DataFrame(list(zip(X, y)))
df.columns = ['close - open', 'class']
data = df['close - open'].values
N = df.shape[0]
df

close - open  class
0    0.000000e+00      1
1    1.389000e-05      1
2   -4.788000e-05     -1
3   -1.050200e-04     -1
4   -6.207000e-05     -1
5    6.201000e-05      1
6    5.501000e-05      1
7   -2.484000e-05     -1
8    1.009000e-05      1
9   -4.031000e-05     -1
10   8.994000e-05      1
11  -3.618000e-05     -1
12   1.070000e-05      1
13   5.325000e-05      1
14  -2.551000e-05     -1
15  -5.980000e-06     -1
16  -2.565000e-05     -1
17   8.394000e-05      1
18  -4.124000e-05     -1
19  -3.051000e-05     -1
20  -1.778000e-05     -1
21  -5.874000e-05     -1
22  -1.895000e-05     -1
23   7.422000e-05      1
24  -4.977000e-05     -1
25   3.190000e-06      1
26  -3.863000e-05     -1
27   4.472000e-05      1
28  -1.718000e-05     -1
29   8.880000e-06      1
..            ...    ...
371 -6.140000e-05     -1
372  2.572000e-05      1
373  6.150000e-06      1
374  5.351000e-05      1
375 -1.625900e-04     -1
376  4.307000e-05      1
377  2.383000e-05      1
378 -1.633200e-04     -1
379 -6.990000e-06     -1
380  4.418000e-05      1
381  9.570000e-06      1
382 -4.671000e-05     -1
383 -1.510000e-05     -1
384  1.213900e-04      1
385  5.070000e-06      1
386 -2.310000e-06     -1
387 -5.280000e-06     -1
388 -5.440000e-06     -1
389  8.740000e-06      1
390  6.000000e-08      1
391  1.000000e-05      1
392  3.856000e-05      1
393 -7.914000e-05     -1
394  8.652000e-05      1
395 -2.500600e-04     -1
396  9.452000e-05      1
397  2.123000e-05      1
398 -5.309000e-05     -1
399  3.510000e-05      1
400  4.100000e-06      1

[401 rows x 2 columns]

In [89]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)
X_train = X_train.reshape(-1, 1)
X_test = X_test.reshape(-1, 1)

In [91]:
X_test

array([[ 3.6540e-05],
       [-5.4000e-07],
       [-3.1260e-05],
       [-1.2850e-05],
       [-5.0700e-05],
       [-4.2270e-05],
       [-2.0690e-05],
       [ 5.0190e-05],
       [-3.5020e-05],
       [-8.7500e-06],
       [-2.2611e-04],
       [ 4.5080e-05],
       [ 2.7460e-05],
       [ 3.8500e-06],
       [ 1.0000e-05],
       [ 8.5970e-05],
       [-6.2500e-05],
       [ 3.3740e-05],
       [-2.9900e-06],
       [ 6.2170e-05],
       [-1.3481e-04],
       [ 5.5010e-05],
       [ 1.7521e-04],
       [ 7.7500e-06],
       [ 3.4170e-05],
       [-1.4930e-05],
       [ 6.4200e-06],
       [ 2.5929e-04],
       [ 3.6590e-05],
       [-3.4010e-05],
       [-1.7780e-05],
       [-4.9770e-05],
       [-1.2990e-05],
       [ 5.3430e-05],
       [ 7.1380e-05],
       [-3.9070e-05],
       [-4.6710e-05],
       [-4.0310e-05],
       [-2.6010e-05],
       [-6.9900e-06],
       [ 7.1400e-06],
       [ 4.5800e-06],
       [-3.8000e-06],
       [ 1.6560e-05],
       [-1.8540e-05],
       [ 9

In [92]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [93]:
X_test

array([[ 3.97439197e-01],
       [-2.42288135e-03],
       [-3.33700202e-01],
       [-1.35171052e-01],
       [-5.43336631e-01],
       [-4.52429476e-01],
       [-2.19715785e-01],
       [ 5.44637615e-01],
       [-3.74247165e-01],
       [-9.09576079e-02],
       [-2.43491719e+00],
       [ 4.89532566e-01],
       [ 2.99522593e-01],
       [ 4.49178555e-02],
       [ 1.11238022e-01],
       [ 9.30480796e-01],
       [-6.70585081e-01],
       [ 3.67244649e-01],
       [-2.88431103e-02],
       [ 6.73827143e-01],
       [-1.45035927e+00],
       [ 5.96615372e-01],
       [ 1.89282416e+00],
       [ 8.69745465e-02],
       [ 3.71881669e-01],
       [-1.57601288e-01],
       [ 7.26321365e-02],
       [ 2.79952328e+00],
       [ 3.97978385e-01],
       [-3.63355561e-01],
       [-1.88335023e-01],
       [-5.33307728e-01],
       [-1.36680780e-01],
       [ 5.79577020e-01],
       [ 7.73145637e-01],
       [-4.17921421e-01],
       [-5.00309401e-01],
       [-4.31293292e-01],
       [-2.7

In [94]:
scores = {}
max_n = 0;
for k in range(2, 13):
    classifier = KNeighborsClassifier(n_neighbors = k)
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    scores[k] = accuracy_score(y_test, y_pred)
     

In [95]:
scores

{2: 1.0,
 3: 1.0,
 4: 1.0,
 5: 1.0,
 6: 1.0,
 7: 0.9917355371900827,
 8: 0.9917355371900827,
 9: 0.9917355371900827,
 10: 1.0,
 11: 1.0,
 12: 1.0}

In [96]:
p = 2 #max

In [97]:
def la_2(data, p, eps = 1e-5):
    Xi = 3 * (p + 1) 
    X = data[np.arange(p) + np.arange(len(data) - p)[:, None]]  
    omega = np.argpartition(np.sum(np.power(X - data[-p:], 2), axis=1), Xi)[:Xi]
    idx = np.arange(p)[:, None] - np.arange(p) <= 0
    Y = np.hstack((np.ones(Xi)[:, None], (X[omega, :, None] * X[omega, None, :])[:, idx]))#  Y*Y(a,B) = Y*X
    params = np.linalg.solve(Y.T @ Y + eps * np.eye(Y.shape[1]), Y.T @ data[omega + p])
    return params, np.sum(params * np.hstack([1, (data[-p:, None] * data[-p:])[idx]]))

In [98]:
def T_steps_prediction(T, X):
    predictions = np.array([])
    X_L = X
    while (T > 0):
        pred = la_2(X_L, p)[1]
        predictions = np.append(predictions, pred)
        X_L = np.append(X_L, pred)
        T -= 1
    return predictions

In [99]:
predictions = T_steps_prediction(50, data)
predictions[predictions > 0], predictions[predictions < 0] = 1, -1

In [100]:
predictions

array([ 1., -1.,  1., -1.,  1.,  1.,  1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.,
       -1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1.,  1., -1.,
       -1., -1.,  1.,  1.,  1.,  1., -1.,  1., -1.,  1., -1.])